version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: idioms-app_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
    
  server:
    image: registry.leaders.estate/idioms:arm64
    #need root to setup nginx
    #user: "1000:1000"
    user: root
    init: true
    volumes:
      - nginx_cache:/var/cache/nginx
    tmpfs:
      - /tmp
      - /var/run

volumes:
  nginx_cache: